# fly.toml app configuration file generated for test-app-server on 2023-05-05T17:18:29+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "test-app-server"
primary_region = "nrt"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
